services:
  db:
    image: postgres:16
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      POSTGRES_USER: www
      POSTGRES_PASSWORD: www
      POSTGRES_DB: www
    ports:
      - "5432:5432"
    volumes:
      - www_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - www_redis:/data

volumes:
  www_pg:
  www_redis:
